WASdev/ci.docker

websphere-liberty/8.5.5/Dockerfile, websphere-liberty/8.5.5/liberty-run, websphere-liberty/8.5.5/license-check
The ENTRYPOINT is now used for the LICENSE check, at which point the CMD
takes over and is executed directly via exec.  This also enables the
user to run arbitrary commands such as "productInfo version" directly.
It also enables a data volume container to be created directly from the
websphere-liberty image rather than something else based on ubuntu (to
get around the original ENTRYPOINT limitation).
=> Fix up ENTRYPOINT/CMD to be more flexible.

websphere-liberty/8.5.5/developer/common/README.md, websphere-liberty/8.5.5/developer/javaee7/README.md, websphere-liberty/8.5.5/developer/kernel/Dockerfile, websphere-liberty/8.5.5/developer/kernel/README.md, websphere-liberty/8.5.5/developer/kernel/view-jre-license, websphere-liberty/8.5.5/developer/webProfile6/README.md, websphere-liberty/8.5.5/developer/webProfile7/README.md, websphere-liberty/beta/Dockerfile, websphere-liberty/beta/README.md, websphere-liberty/beta/view-jre-license
Export controls are now in place on Docker Hub so merging IBM JRE back in to all images.
=> Merge ibmjre back in

websphere-liberty/8.5.5/developer/javaee7/Dockerfile, websphere-liberty/8.5.5/developer/javaee7/server.xml, websphere-liberty/8.5.5/developer/webProfile6/Dockerfile, websphere-liberty/8.5.5/developer/webProfile6/docker-server, websphere-liberty/8.5.5/developer/webProfile6/server.xml, websphere-liberty/8.5.5/developer/webProfile7/Dockerfile, websphere-liberty/8.5.5/developer/webProfile7/docker-server, websphere-liberty/8.5.5/developer/webProfile7/server.xml
Not sure if there is a neater way to preserve double quote attributes in the docker-server script.
=> Runtime keystore password generation and server.xml update

websphere-liberty/8.5.5/developer/javaee7/Dockerfile, websphere-liberty/8.5.5/developer/kernel/Dockerfile, websphere-liberty/8.5.5/developer/webProfile6/Dockerfile, websphere-liberty/8.5.5/developer/webProfile7/Dockerfile, websphere-liberty/8.5.5/production-install/add/Dockerfile, websphere-liberty/8.5.5/production-install/wget/Dockerfile, websphere-liberty/beta/Dockerfile
As per https://github.com/WASdev/ci.docker/issues/69, installUtility when run against a server configuration is leaving behind a logs directory in /config/logs which, as well as wasting space, is confusing to users when the actual server logs will end up in /logs. Cleaning up this directory and also creating the directory /logs to help signpost this location.
=> Remove logs directory left by installUtility

beta/Dockerfile, ga/developer/javaee7/Dockerfile, ga/developer/kernel/Dockerfile, ga/developer/webProfile6/Dockerfile, ga/developer/webProfile7/Dockerfile, test/verify.sh
Added a test to check if workarea directory is present. Removed workarea in Dockerfile for beta, kernel, javaee, webProfile6 and webProfile7. Removed "touch" command from javaee7 and webProfile7 Dockerfiles because workarea is no longer present. Increased timeout for liberty to start while testing from 60 seconds to 120.
=> Removed workarea and added test

beta/Dockerfile, tools/syncRepository.sh
The syncRepo script was throwing an error due to the fact that we are using the -f variable that is now deprecated.
=> Fix syncrepo script and update beta

ga/developer/kernel/Dockerfile, ga/developer/kernel/docker-server
Add product labels required by Product Insights and LICENSE environment variable that can be used to suppress the developer licensed message. The latter will be used by the Helm chart in IBM Cloud Private where the image will be licensed for production use.
=> Product labels and LICENSE variable

beta/Dockerfile
Update websphere-liberty version to 2018.3.0.0 (March beta).
=> Update websphere-liberty beta to 2018.3.0.0

ga/developer/javaee7/Dockerfile, ga/developer/microProfile/Dockerfile, ga/developer/webProfile6/Dockerfile, ga/developer/webProfile7/Dockerfile, test/verify.sh
Adding a server start/stop to the images (except kernel, since there's no server.xml in there) to improve startup time.  There's a tradeoff with image sizes, as noted below:
microprofile:  increase of 63 MB.   startup from 8 seconds to 3 seconds
webProfile7:   increase of 64 MB.   startup from 9 seconds to 4 seconds
javaee7:      increase of  63 MB.   startup from 12 seconds to 5 seconds
=> Prime the server to improve startup performance

ga/developer/centos/Dockerfile
Adding a dockerfile that builds a WebSphere Liberty image based on CentOS, with a non-root user called `wlp`. 
It uses a multi-stage build approach by referencing external images. 
=> Adding CentOS dockerfile

ga/developer/rhel/kernel/Dockerfile, ga/developer/rhel/kernel/docker-server
Move creation of `/config/configDropins/defaults` directory into the Dockerfile instead of `docker-server` script to avoid file permission issues in ICP.
=> Moved configDropins dir creation to Dockerfile

beta/Dockerfile, ga/18.0.0.3/centos/Dockerfile, ga/18.0.0.3/kernel/Dockerfile, ga/18.0.0.4/kernel/Dockerfile
Fixes #213
Need to specify the `/usr/sbin/nologin` because there is no `/sbin/nologin` in the Ubuntu image. 
Although CentOS has both `/sbin/nologin` and `/usr/sbin/nologin`, I think it is better to specify `/usr/sbin/nologin` for consistency.
=> Specify correct login shell when adding user

ga/19.0.0.1/kernel/licenses/en.html, ga/19.0.0.1/kernel/licenses/non_ibm_license.html
The Liberty 19.0.0.1 product was shipped with the 18.0.0.4 license files except for notices.html.  Not totally sure why but I'm updating the Docker images to match.
=> Revert 19.0.0.1 license files to 18.0.0.4 version

ga/18.0.0.3/javaee7/Dockerfile, ga/18.0.0.3/javaee8/Dockerfile, ga/18.0.0.3/kernel/Dockerfile, ga/18.0.0.3/microProfile1/Dockerfile, ga/18.0.0.3/microProfile2/Dockerfile, ga/18.0.0.3/springBoot1/Dockerfile, ga/18.0.0.3/springBoot2/Dockerfile, ga/18.0.0.3/webProfile7/Dockerfile, ga/18.0.0.3/webProfile8/Dockerfile, ga/18.0.0.4/javaee7/Dockerfile, ga/18.0.0.4/javaee8/Dockerfile, ga/18.0.0.4/kernel/Dockerfile, ga/18.0.0.4/microProfile1/Dockerfile, ga/18.0.0.4/microProfile2/Dockerfile, ga/18.0.0.4/oidcProvider/Dockerfile, ga/18.0.0.4/springBoot1/Dockerfile, ga/18.0.0.4/springBoot2/Dockerfile, ga/18.0.0.4/webProfile7/Dockerfile, ga/18.0.0.4/webProfile8/Dockerfile, ga/19.0.0.1/javaee7/Dockerfile, ga/19.0.0.1/javaee8/Dockerfile, ga/19.0.0.1/kernel/Dockerfile, ga/19.0.0.1/microProfile1/Dockerfile, ga/19.0.0.1/microProfile2/Dockerfile, ga/19.0.0.1/oidcProvider/Dockerfile, ga/19.0.0.1/springBoot1/Dockerfile, ga/19.0.0.1/springBoot2/Dockerfile, ga/19.0.0.1/webProfile7/Dockerfile, ga/19.0.0.1/webProfile8/Dockerfile
Our current images cannot run as-is with users other than `1001`, which is an issue for platforms such as OpenShift Online.  
The main issue is with the server warmup, because classes are cached as user `1001`, but access by another random user.  Very easy to reproduce, just run `docker run -u 13001 websphere-liberty` and see the crash.
The fix:
- applies the right permissions to folders such as `workarea` can be access by another user in the root group
- use the appropriate shared class setting so that other users can access the cache
=> Updating permissions for server cache

test/verify.sh
wget is failing in testFeatureList with ssl handshake errors because of BusyBox wget in Alpine.  Adding a call to install GNU wget instead, which should work properly.
=> Fix image download errors in testFeatureList

ga/18.0.0.3/kernel/Dockerfile, ga/18.0.0.3/springBoot1/Dockerfile, ga/18.0.0.3/springBoot2/Dockerfile, ga/18.0.0.4/kernel/Dockerfile, ga/18.0.0.4/springBoot1/Dockerfile, ga/18.0.0.4/springBoot2/Dockerfile, ga/19.0.0.3/kernel/Dockerfile, ga/19.0.0.3/springBoot1/Dockerfile, ga/19.0.0.3/springBoot2/Dockerfile
Tom Watson and Anjum Fatima pointed out that there is a problem with the kernel Dockerfile creating the /lib.index.cache directory when it should really be a symlink to /opt/ibm/wlp/usr/shared/resources/lib.index.cache.
Since that directory is only used by the springBoot images, we are moving the work related to that directory into the springBoot Dockerfiles.
=> Move lib.index.cache directory work to springBoot files

beta/Dockerfile, ga/18.0.0.3/centos/Dockerfile, ga/18.0.0.3/kernel/Dockerfile, ga/18.0.0.3/springBoot1/Dockerfile, ga/18.0.0.3/springBoot2/Dockerfile, ga/18.0.0.4/centos/Dockerfile, ga/18.0.0.4/kernel/Dockerfile, ga/18.0.0.4/springBoot1/Dockerfile, ga/18.0.0.4/springBoot2/Dockerfile, ga/19.0.0.3/kernel/Dockerfile, ga/19.0.0.3/kernel/Dockerfile.centos, ga/19.0.0.3/springBoot1/Dockerfile, ga/19.0.0.3/springBoot2/Dockerfile
The springBoot1 and 2 builds are breaking because of the change under #243. The /lib.index.cache directory needs to be created as the root user due to permissions issues, so we need to set it up in the kernel images which will therefore get it into the springBoot images where it is needed.
=> Set up lib.index.cache dir in kernel images

ga/18.0.0.4/kernel/helpers/build/configure.sh, ga/19.0.0.3/kernel/helpers/build/configure.sh
`installUtility` will often return code 22 when a user feature is already installed. After changing the scripts, I tested the changes locally and now the output looks like this
```
Preparing assets for installation. This process might take several minutes to complete.
CWWKF1250I: The following assets already exist: [usr:opentracingZipkin-0.31]. They will not be reinstalled. To modify an existing feature, you must manually uninstall it first.
+ '[' 22 -ne 22 ']'
Removing intermediate container 5c4b9018c913
---> 8f0360fd02a5
Successfully built 8f0360fd02a5
```
=> Modified configure.sh to ignore rc=22

ga/19.0.0.3/kernel/Dockerfile, ga/19.0.0.4/kernel/Dockerfile
This PR is for issue #224 
Proactively added `openssl` to the Dockerfile.
=> Add openssl to Dockerfile

ga/19.0.0.3/kernel/Dockerfile, ga/19.0.0.4/kernel/Dockerfile, ga/19.0.0.4/kernel/Dockerfile.ubi-min
This PR is related to issue #247
Modified the Dockerfile to install wget which is already installed in IBM Java image and will be uninstalld after use.
In this way, the size can be reduced when wget is removed from the IBM Java image in the future.
=> Install wget before uninstall it

beta/Dockerfile, ga/18.0.0.4/centos/Dockerfile, ga/18.0.0.4/kernel/Dockerfile, ga/18.0.0.4/kernel/helpers/build/configure.sh, ga/19.0.0.3/kernel/Dockerfile, ga/19.0.0.3/kernel/Dockerfile.centos, ga/19.0.0.3/kernel/helpers/build/configure.sh, ga/19.0.0.5/kernel/Dockerfile, ga/19.0.0.5/kernel/Dockerfile.centos, ga/19.0.0.5/kernel/Dockerfile.ubi-min, ga/19.0.0.5/kernel/helpers/build/configure.sh
Fixing issues pointed out under https://github.com/docker-library/official-images/pull/5951 and docker-library/official-images#5950
Removing --update from the apk add --no-cache calls.
Updating image labels to comply with https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md
Removing bad RUN in configure.sh server start/stop line.
=> Fix issues with images upgrading to 19.0.0.5

ga/19.0.0.x/kernel/Dockerfile.ubi-min
The Red Hat certification scan is expecting a few labels to be present, and are not yet using the `org.opencontainers.image.*` labels, so adding the old labels back in to pass certification.
=> Adding labels

README.md, ga/latest/kernel/helpers/build/configuration_snippets/transportSecurity.xml, ga/latest/kernel/helpers/build/configure.sh
Added the transportSecurity.xml file into the configuration_snippets folder.
The transportSecurity feature includes the ssl feature thus superseding it.
https://www.ibm.com/support/knowledgecenter/en/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_feature_transportSecurity-1.0.html
=> Add transportSecurity feature to kernel image

test/build.sh, test/buildAll.sh, test/verify.sh
Newer releases of Fedora and RHEL use the 'podman' tool to build and
run OCI container images, not 'docker'.  These changes enable the use
of podman when available, simplifying build/test for Fedora/RHEL
users.  You can override this choice by setting the DOCKER environment
variable.
=> Use podman when available.

ga/latest/kernel/helpers/build/configuration_snippets/keystore.xml, ga/latest/kernel/helpers/build/configuration_snippets/tls.xml, ga/latest/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/runtime/docker-server.sh
Make use of defaults folder for keystore.xml snippet, generate it unless TLS and SSL are false
Separate TLS feature into separate snippet 
Fix for #287
=> Add keystore file to defaults instead of overrides

ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8
- Travis runs into intermittent issues with root's permission to /usr/bin on ppc64le VMs. Likely from some setup issue Travis encounters with this particular architecture.
- Given that the build is already running as root, the added command is redundant in other scenarios.
=> Fix Permissions Issue in Travis for UBI Build

ga/19.0.0.12/kernel/helpers/runtime/docker-server.sh, ga/latest/kernel/helpers/runtime/docker-server.sh
WAS Liberty port of https://github.com/OpenLiberty/ci.docker/pull/131
=> Generate random keystore with /dev/urandom instead of openssl

README.md, ga/19.0.0.12/kernel/helpers/build/configure.sh, ga/19.0.0.9/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/configure.sh, test/test-stock-quote/Dockerfile, test/test-stock-trader/Dockerfile
* Redirects the standard output from `configure.sh` based on how the user specifies the build argument `VERBOSE`
* If the user sets `VERBOSE` to `true` all output from `configure.sh` is outputted.
* Changes the directions for the `Dockerfile` in the `README` to include the default `ARG VERBOSE`
=> Adding the verbose option

README.md, ga/20.0.0.3/full/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.3/full/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.3/full/Dockerfile.ubi.ibmjava8, ga/20.0.0.3/full/Dockerfile.ubuntu.ibmjava8, ga/20.0.0.3/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.3/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.3/kernel/Dockerfile.ubi.ibmjava8, ga/20.0.0.3/kernel/Dockerfile.ubuntu.ibmjava8, ga/20.0.0.3/kernel/helpers/build/configure.sh, ga/20.0.0.3/kernel/helpers/build/populate_scc.sh, ga/latest/full/Dockerfile.ubi.adoptopenjdk11, ga/latest/full/Dockerfile.ubi.adoptopenjdk8, ga/latest/full/Dockerfile.ubi.ibmjava8, ga/latest/full/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/populate_scc.sh
This patch
- introduces the populate_scc.sh script to manage creating and populating
OpenJ9 SCC cache layers,
- adds multi-layer SCCs to the kernel and full OpenJ9 and IBM JDK images,
- and allows for user images that call configure.sh to add their data to
the existing caches.
=> Add OpenJ9 multi-layer SCCs to images

ga/19.0.0.12/kernel/Dockerfile.ubi.adoptopenjdk11, ga/19.0.0.12/kernel/Dockerfile.ubi.adoptopenjdk8, ga/19.0.0.12/kernel/Dockerfile.ubi.ibmjava8, ga/19.0.0.12/kernel/Dockerfile.ubuntu.ibmjava8, ga/20.0.0.3/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.3/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.3/kernel/Dockerfile.ubi.ibmjava8, ga/20.0.0.3/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8
* Update existing labels to match the new base OS/Java images
* Add missing labels to Ubuntu based images for version and descriptions
Fixes #327
=> Update image labels for base image changes

ga/20.0.0.6/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.6/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.6/kernel/helpers/build/populate_scc.sh, ga/20.0.0.9/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.9/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.9/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/helpers/build/populate_scc.sh
Note: This fix corresponds to a similar one in Open Liberty: https://github.com/OpenLiberty/ci.docker/pull/204.
On some systems trying to use the OpenJ9 SCC leads to
permission denied errors, despite file permissions being
observably correct.
For the time being we'll ignore the OpenJ9 SCC and
continue to build our own SCC layers. In order to do this
we switch to setting/using the OPENJ9_JAVA_OPTIONS
env var in order to override the OpenJ9 image and move
away from IBM_JAVA_OPTIONS, which is deprecated anyway.
=> Prefer Liberty SCC to OpenJ9 SCC

ga/20.0.0.11/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.11/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.11/kernel/Dockerfile.ubi.ibmjava8, ga/20.0.0.11/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8
non_ibm_license.html was accidentally pluralized.
=> Fix file name issue in security check for license files

ga/20.0.0.9/kernel/Dockerfile.ubi.adoptopenjdk11, ga/20.0.0.9/kernel/Dockerfile.ubi.adoptopenjdk8, ga/20.0.0.9/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/helpers/build/populate_scc.sh
If /opt/java/.scc exists and is readable, assume that an OpenJ9 system
SCC named "openj9_system_scc" exists and build the current image's
SCC layer on top of it. If it doesn't exist or is not readable,
continue to build on the Liberty SCC named "liberty" in
/output/.classCache.
The above will result in images based on IBM JDK continuing to build
a Liberty SCC (as the IBM JDK image does not ship with an SCC) and
OpenJ9 based images building on the OpenJ9 system SCC, except when
directory permissions prevent non-root access.
This last condition is to allow for gracefully handling older OpenJ9
images that did not allow for non-root SCC access.
=> Build on OpenJ9 system SCC when possible

ga/latest/full/Dockerfile.ubuntu.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubuntu.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8
- Add OpenJ9 Java 11 support on Ubuntu
- Fixed minor bug in ga/latest/kernel/Dockerfile.ubuntu.ibmjava8 where wlp.zip is downloaded twice
=> Add Ubuntu + OpenJ9 11 images

ga/latest/kernel/helpers/build/configure.sh
This change equivalent to https://github.com/OpenLiberty/ci.docker/pull/228. Build and runtime performance deltas for this change are in line with what was observed for Open Liberty running the same benchmarks (Acme Air and DT7).
Currently every image in the stack runs the server 4 times to build
its SCC layer. The final 2 iterations are optional but allow for the
refinement of profiling information. This patch reduces the number
of optional iterations for app images from 2 to 1 to reduce build
times on the basis that it does not sacrifice much, if any,
start-up performance. It does not affect the number of iterations
used for server SCC layers.
=> Reduce SCC build time for app images

ga/21.0.0.1/kernel/Dockerfile.ubi.adoptopenjdk11, ga/21.0.0.1/kernel/Dockerfile.ubi.adoptopenjdk8, ga/21.0.0.1/kernel/Dockerfile.ubuntu.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubuntu.adoptopenjdk11
Based on https://github.com/OpenLiberty/ci.docker/pull/238
Previously OpenJ9 Docker images set OPENJ9_JAVA_OPTIONS to a value
that enabled the use of the system SCC at runtime. Recent OpenJ9 images
have stopped setting it in favour of JAVA_TOOL_OPTIONS, which Liberty is
currently not aware of. This causes the Liberty server script to set
OPENJ9_JAVA_OPTIONS to a default value that does not include the system
SCC.
=> Set OPENJ9_JAVA_OPTIONS env var for containers

ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8
Part of the fix for https://github.com/WASdev/ci.docker/issues/387.
Per Tom Watson, there isn't a good reason to have this set to true (the default) in a docker env, so setting to false.
Also, this won't do much until 21.0.0.4, so no big reason to put it into previous releases.
=> set osgi.checkConfiguration=false

ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8
We already do this for OpenJ9. This helps startup time a small amount.
=> Make SCC readonly for IBM JDK8

README.md, ga/21.0.0.3/full/Dockerfile.ubi.adoptopenjdk11, ga/21.0.0.3/full/Dockerfile.ubi.adoptopenjdk8, ga/21.0.0.3/full/Dockerfile.ubi.ibmjava8, ga/21.0.0.6/full/Dockerfile.ubi.adoptopenjdk11, ga/21.0.0.6/full/Dockerfile.ubi.adoptopenjdk8, ga/21.0.0.6/full/Dockerfile.ubi.ibmjava8, ga/21.0.0.8/full/Dockerfile.ubi.adoptopenjdk11, ga/21.0.0.8/full/Dockerfile.ubi.adoptopenjdk8, ga/21.0.0.8/full/Dockerfile.ubi.ibmjava8, ga/latest/full/Dockerfile.ubi.adoptopenjdk11, ga/latest/full/Dockerfile.ubi.adoptopenjdk8, ga/latest/full/Dockerfile.ubi.ibmjava8
We need the images that build on top of the kernel images to make sure they are pulling that image from the proper icr.io repository, instead of the Docker Hub one.
=> Update Dockerfiles to build on top of the correct images from icr.io

README.md, SECURITY.md, beta/README.md, docs/icr-images.md, ga/21.0.0.11/README.md, ga/21.0.0.11/full/README.md, ga/21.0.0.11/kernel/README.md, ga/21.0.0.11/oidcProvider/README.md, ga/21.0.0.6/README.md, ga/21.0.0.6/full/README.md, ga/21.0.0.6/kernel/README.md, ga/21.0.0.6/oidcProvider/README.md, ga/21.0.0.9/README.md, ga/21.0.0.9/full/README.md, ga/21.0.0.9/kernel/README.md, ga/21.0.0.9/oidcProvider/README.md, ga/README.md, ga/latest/README.md, ga/latest/full/README.md, ga/latest/kernel/README.md, ga/latest/oidcProvider/README.md, ga/production-upgrade/README.md, test/build.sh, test/buildAll.sh
- Document the images in IBM Container Registry (icr.io) 
- Replace references to Docker with container
Signed-off-by: leochr <leojc@ca.ibm.com>
=> Document images in ICR and use containers instead of Docker

ga/21.0.0.12/full/Dockerfile.ubuntu.openjdk17, ga/21.0.0.12/images.txt, ga/21.0.0.12/kernel/Dockerfile.ubuntu.openjdk17, ga/22.0.0.1/full/Dockerfile.ubuntu.openjdk17, ga/22.0.0.1/images.txt, ga/22.0.0.1/kernel/Dockerfile.ubuntu.openjdk17, ga/latest/full/Dockerfile.ubuntu.openjdk17, ga/latest/images.txt, ga/latest/kernel/Dockerfile.ubuntu.openjdk17
This PR adds the Dockerfile.ubuntu.openjdk17 files to build a container image with WebSphere Liberty and Java 17 (full, kernel)
=> Provide a Dockerfile for WebSphere Liberty with ubuntu and Java 17

ga/21.0.0.12/full/Dockerfile.ubi.openjdk17, ga/21.0.0.12/images.txt, ga/21.0.0.12/kernel/Dockerfile.ubi.openjdk11, ga/21.0.0.12/kernel/Dockerfile.ubi.openjdk17, ga/21.0.0.9/kernel/Dockerfile.ubi.openjdk11, ga/21.0.0.9/kernel/Dockerfile.ubi.openjdk8, ga/22.0.0.1/full/Dockerfile.ubi.openjdk17, ga/22.0.0.1/images.txt, ga/22.0.0.1/kernel/Dockerfile.ubi.openjdk11, ga/22.0.0.1/kernel/Dockerfile.ubi.openjdk17, ga/22.0.0.1/kernel/Dockerfile.ubi.openjdk8, ga/latest/full/Dockerfile.ubi.openjdk17, ga/latest/images.txt, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk17, ga/latest/kernel/Dockerfile.ubi.openjdk8
This PR adds Dockerfiles to build container images for Open Liberty with icr.io UBI images and Java 17 (full, kernel)
=> Provide a Dockerfile for WebSphere Liberty with icr.io UBI images and Java 17

ga/21.0.0.12/full/Dockerfile.ubi.ibmjava8, ga/21.0.0.12/full/Dockerfile.ubi.openjdk11, ga/21.0.0.12/full/Dockerfile.ubi.openjdk17, ga/21.0.0.12/full/Dockerfile.ubi.openjdk8, ga/21.0.0.9/full/Dockerfile.ubi.ibmjava8, ga/21.0.0.9/full/Dockerfile.ubi.openjdk11, ga/21.0.0.9/full/Dockerfile.ubi.openjdk8, ga/22.0.0.1/full/Dockerfile.ubi.ibmjava8, ga/22.0.0.1/full/Dockerfile.ubi.openjdk11, ga/22.0.0.1/full/Dockerfile.ubi.openjdk17, ga/22.0.0.1/full/Dockerfile.ubi.openjdk8, ga/latest/full/Dockerfile.ubi.ibmjava8, ga/latest/full/Dockerfile.ubi.openjdk11, ga/latest/full/Dockerfile.ubi.openjdk17, ga/latest/full/Dockerfile.ubi.openjdk8, test/buildAll.sh
- Images are first built in staging environment. Hence the _kernel_ image specified as parent image in Dockerfiles of _full_ images wouldn't exist yet. Allow the parent image to be passed in as a build argument.
Only changed UBI images since we only build them. Ubuntu images are built by Docker Hub, so left them as-is for now.
- Added Java 17 tag to build script.
=> Support dynamically changing parent image

ga/21.0.0.12/kernel/helpers/build/populate_scc.sh, ga/22.0.0.3/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/helpers/build/populate_scc.sh
32-bit IBM Java VMs don't support multi-layered SCCs.
Fixes #403
=> Don't create SCCs on 32-bit IBM Java

README.md, ga/22.0.0.12/kernel/helpers/build/configure.sh, ga/22.0.0.9/kernel/helpers/build/configure.sh, ga/23.0.0.1/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/configure.sh
Users who create container images for their Liberty based apps are encouraged to use "RUN configure.sh" in the Dockerfile for their containerized app. In turn, this script will call `populate_scc.sh` which will create a shared class cached (SCC) populated with Java classes and methods used during app start-up. Currently, the populate_scc.sh script uses a fixed size (80m) for the embedded SCC. Moreover, the variable `TRIM_SCC` that controls whether or not the SCC is trimmed to just the right size for the classes/methods used during start-up is set to "yes".
To take advantage of the AOT cache from the Semeru Cloud Compiler, the client JVM (which runs a Liberty app) needs to have a SCC with some empty space in it, to be able to add new AOT methods received from the Semeru Cloud Compiler. …
=> Enable user to specify size of SCC embedded in container

ga/23.0.0.6/full/Dockerfile.ubuntu.ibmjava8, ga/23.0.0.6/full/Dockerfile.ubuntu.openjdk11, ga/23.0.0.6/full/Dockerfile.ubuntu.openjdk17, ga/latest/full/Dockerfile.ubuntu.ibmjava8, ga/latest/full/Dockerfile.ubuntu.openjdk11, ga/latest/full/Dockerfile.ubuntu.openjdk17
Seems like there's logic in the Docker builds that appends `:latest` to an image that it thinks doesn't have a tag, which results in it trying to pull down things like `websphere-liberty:kernel-java17-openj9:latest`
=> Update Ubuntu full images to use tag in FROM

ga/23.0.0.3/kernel/helpers/build/populate_scc.sh, ga/23.0.0.6/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/helpers/build/populate_scc.sh
If the server fails to start when populating the SCC we should gracefully fail the build. Because the populate_scc.sh script sets the -e shell option, the shell will exit if any command returns non-zero, except in certain cases.
The populate_scc.sh script starts and stops the server in a compound expression using &&, which is one such case where a non-zero return from `server start` will be ignored.
Executing `server start` and `server stop` separately fixes this and has the desired behaviour; if the server fails to start execution will stop and the build will fail, rather than continuing on and leading to undefined behaviour.
=> Fail if server cannot start when populating SCC

ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk17, ga/latest/kernel/Dockerfile.ubi.openjdk8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.openjdk11, ga/latest/kernel/Dockerfile.ubuntu.openjdk17
The `/liberty` symlink of WebSphere Liberty points to `/opt/ibm` while Open Liberty's symlink points to `/opt/ol/wlp`. This discrepancy defeats the purpose of having this common path/symlink. Change the WebSphere Liberty's symlink to `/opt/ibm/wlp`. To minimize potential disruption to users, introduce this change in a monthly release (as opposed to a quarterly release) of Liberty. 
PR for https://github.com/WASdev/ci.docker/issues/474
=> Change /liberty symlink from /opt/ibm to /opt/ibm/wlp

ga/latest/kernel/helpers/build/checkpoint.sh
During checkpoint the current user creates
resources and directories for which the restore
user needs permission to read and write.
This change fixes up the permissions to allow
a different from the checkpoint user to restore
the process.
=> Fix up permissions when a different user restores

.github/workflows/update_files_for_release.yml, create-new-release.sh
This addresses Leo's comment at https://github.com/WASdev/ci.docker/pull/568#discussion_r1394517850 (the comment is still valid even though I had to close PR) and also a minor improvement to the build label placeholder text.
=> GitHub Action release updates automation fixes

ga/24.0.0.1/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/helpers/build/populate_scc.sh
Add `-XX:+IProfileDuringStartupPhase` option to the populate scc script
When populating the SCC during the build of both the Liberty and app containers, the JVM can disable the IProfiler collection during JVM startup to enhance startup time, but this limits the amount of IProfiler information that can be stored into the SCC.
OpenJ9 can now support `-XX:+IProfileDuringStartupPhase` to enforce collecting IProfiler information during startup and better populate the SCC, which can be used in the `populate_scc.sh` script.
The option will be ignored if the used OpenJ9 build does not have the new option implemented.
Effect is larger amount of JIT Data in the SCC after a `populate_scc` run.
There’s no functional implications on Liberty, and performance effect is application dependent.
> In …
=> Use `-XX:+IProfileDuringStartupPhase` in `populate_scc.sh` scripts

ga/24.0.0.2/kernel/Dockerfile.ubi.ibmjava8, ga/24.0.0.2/kernel/Dockerfile.ubi.openjdk11, ga/24.0.0.2/kernel/Dockerfile.ubi.openjdk17, ga/24.0.0.2/kernel/Dockerfile.ubi.openjdk21, ga/24.0.0.2/kernel/Dockerfile.ubi.openjdk8, ga/24.0.0.2/kernel/Dockerfile.ubuntu.ibmjava8, ga/24.0.0.2/kernel/Dockerfile.ubuntu.openjdk11, ga/24.0.0.2/kernel/Dockerfile.ubuntu.openjdk17, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk17, ga/latest/kernel/Dockerfile.ubi.openjdk21, ga/latest/kernel/Dockerfile.ubi.openjdk8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.openjdk11, ga/latest/kernel/Dockerfile.ubuntu.openjdk17
Update with specific values for build label and file checksum.
=> Update LIBERTY_BUILD_LABEL and LIBERTY_SHA with real values

README.md, ga/24.0.0.4/kernel/helpers/build/configure.sh, ga/24.0.0.4/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/populate_scc.sh
Add call to the OpenAPI endpoint during SCC generation. This will improve first request performance.
=> Add call to OpenAPI endpoint

ga/24.0.0.10/kernel/helpers/runtime/docker-server.sh, ga/24.0.0.6/kernel/helpers/runtime/docker-server.sh, ga/24.0.0.9/kernel/helpers/runtime/docker-server.sh, ga/latest/kernel/helpers/runtime/docker-server.sh
For https://github.com/WASdev/ci.docker/issues/645.
=> Force /tmp/certs dir creation
