WASdev/ci.docker

websphere-liberty/8.5.5/developer/Dockerfile, websphere-liberty/beta/Dockerfile
Update Java version (and handle carriage returns that appear to have got in to the Liberty index.yml)
=> Move to Java 7.1 SR2 FP10

websphere-liberty/beta/Dockerfile
WebSphere Liberty beta version updated
=> Beta version update

websphere-liberty/8.5.5/developer/kernel/Dockerfile, websphere-liberty/8.5.5/production-install/add/Dockerfile, websphere-liberty/8.5.5/production-install/wget/Dockerfile, websphere-liberty/beta/Dockerfile
Fix this issue for all Dockerfiles and use environment variable across the board.
=> Delete .classCache from WLP_OUTPUT_DIR

websphere-liberty/8.5.5/developer/javaee7/Dockerfile, websphere-liberty/8.5.5/developer/webProfile7/Dockerfile, websphere-liberty/8.5.5/developer/webProfile7/docker-server
Not sure about some of the deletions, I think it's removing white space at the end of the lines? This may fail the feature tests again but it has passed locally.
@davidcurrie In terms of the code I chose not to write a separate test for the stopping, opting to add it to the clean up instead. This is the easiest way I could see to do it without having to rewrite most of the tests.
I managed to get a local failure of the feature tests so will raise an issue and attach the diff.txt produced, hopefully we can get this sorted.
=> Feature failure fix and password escaping fix

websphere-liberty/8.5.5/developer/webProfile6/Dockerfile, websphere-liberty/8.5.5/developer/webProfile6/docker-server, websphere-liberty/test/buildAndVerify.sh
Split this commit from my previous PR
=> Expanded tests for logs errors and clean stops

websphere-liberty/8.5.5/developer/kernel/Dockerfile, websphere-liberty/8.5.5/production-install/add/Dockerfile, websphere-liberty/8.5.5/production-install/wget/Dockerfile, websphere-liberty/beta/Dockerfile, websphere-liberty/test/build.sh
Please don't pull until we have confirmation of the SOE results on 16.04.
=> Move to ubuntu:16.04 base

ga/developer/javaee7/Dockerfile, ga/developer/kernel/Dockerfile, ga/developer/webProfile6/Dockerfile, ga/developer/webProfile7/Dockerfile, test/verify.sh
=> Internal build changes

beta/Dockerfile
=> updated to use latest beta

ga/developer/kernel/Dockerfile, ga/developer/microProfile/Dockerfile, test/microProfile.txt
=> 16.0.0.3 and microProfile update

beta/Dockerfile, test/beta.txt
A change to provide the latest beta update.
=> beta update

test/verify.sh
microProfile has now been added the index.yml but it is using the key microProfile1
=> Map microProfile tag to microProfile1 download

beta/Dockerfile
Update the Dockerfile for the Beta to get the latest binaries.
=> Update to the latest beta

beta/Dockerfile
Update beta version to 2017.12.0_0
=> Update to December Liberty Beta

beta/Dockerfile, beta/server.xml
Update beta version and webProfile feature version.
=> Update beta to 2018.2.0.0

ga/developer/kernel/Dockerfile, ga/developer/microProfile/Dockerfile, ga/developer/microProfile/server.xml, ga/developer/webProfile7/Dockerfile
Update GA product version to 18.0.0.1.
=> Update to 18.0.0.1

beta/Dockerfile
=> Update websphere-liberty beta to 2018.4.0.0

ga/developer/javaee7/Dockerfile, ga/developer/microProfile/Dockerfile, ga/developer/webProfile6/Dockerfile, ga/developer/webProfile7/Dockerfile, test/verify.sh
=> Adding ONBUILD for server priming

beta/Dockerfile, ga/developer/centos/Dockerfile, ga/developer/kernel/Dockerfile, ga/developer/rhel/Dockerfile.rhel, ga/developer/rhel/Dockerfile.rhelatomic, ga/production-install/add/Dockerfile, ga/production-install/wget/Dockerfile
Fixes #145 , and fixes some `yum update` issues I noticed (was missing the `-y` flag).
=> Liberty link

ga/developer/rhel/Dockerfile.rhel, ga/developer/rhel/Dockerfile.rhelatomic, ga/developer/rhel/README.md, ga/developer/rhel/docker-build
Updates for Red Hat certification
=> RHEL updates

ga/developer/README.md, ga/developer/centos/README.md, ga/developer/javaee8/Dockerfile, ga/developer/javaee8/README.md, ga/developer/javaee8/server.xml, ga/developer/rhel/Dockerfile.rhel, ga/developer/rhel/Dockerfile.rhelatomic, ga/developer/rhel/README.md, ga/developer/webProfile8/Dockerfile, ga/developer/webProfile8/README.md, ga/developer/webProfile8/server.xml, test/images.txt, test/verify.sh, tools/syncRepository.sh
- Add javaee8 and webProfile8
- Update list of test images and sync repository (tools) to include EE8
=> Java EE8 Support

beta/Dockerfile
Updating to newly release August beta.
=> Update beta to version 2018.8.0.0

beta/Dockerfile, ga/developer/kernel/Dockerfile
Updating `websphere-liberty` images to run as non-root users.
=> Support non-root containers

ga/18.0.0.3/javaee7/Dockerfile, ga/18.0.0.3/javaee8/Dockerfile, ga/18.0.0.3/microProfile1/Dockerfile, ga/18.0.0.3/microProfile2/Dockerfile, ga/18.0.0.3/springBoot1/Dockerfile, ga/18.0.0.3/springBoot2/Dockerfile, ga/18.0.0.3/webProfile6/Dockerfile, ga/18.0.0.3/webProfile7/Dockerfile, ga/18.0.0.3/webProfile8/Dockerfile
Removing the logs from the server warmup.
=> Cleaning logs from image

beta/Dockerfile
Updating to the new 2018.12.0.0 beta.
=> Update beta to 2018.12.0.0

README.md, ga/18.0.0.4/kernel/helpers/build/configuration_snippets/iiop-endpoint.xml, ga/18.0.0.4/kernel/helpers/build/configuration_snippets/iiop-ssl-endpoint.xml, ga/18.0.0.4/kernel/helpers/build/configuration_snippets/jms-endpoint.xml, ga/18.0.0.4/kernel/helpers/build/configuration_snippets/jms-ssl-endpoint.xml, ga/18.0.0.4/kernel/helpers/build/configure.sh
PR for https://github.ibm.com/WASCloudPrivate/roadmap-cloudpaks/issues/298
=> Add config snippets for iiop and jms endpoint options

README.md, ga/18.0.0.4/kernel/helpers/runtime/docker-server.sh
Added instruction on how to apply a license to get production support.
=> Updated README.md

ga/18.0.0.4/oidcProvider/Dockerfile, ga/18.0.0.4/oidcProvider/README.md, ga/18.0.0.4/oidcProvider/docker-server.sh, ga/18.0.0.4/oidcProvider/server.xml
=> Initial OIDC stuff

ga/18.0.0.3/kernel/Dockerfile, ga/18.0.0.4/kernel/Dockerfile, ga/19.0.0.2/kernel/Dockerfile, ga/19.0.0.2/kernel/Dockerfile.centos
Adding BuildLabel to Liberty Docker images on Docker Hub to help with testing and debug.
=> Add BuildLabel to Docker Hub images

ga/19.0.0.3/javaee8/Dockerfile, ga/19.0.0.3/microProfile2/Dockerfile, ga/19.0.0.3/microProfile2/server.xml
Updating the microProfile2 and javaee8 images to include the microProfile-2.2 feature.
=> Update to microProfile-2.2

ga/18.0.0.3/centos/Dockerfile, ga/18.0.0.4/centos/Dockerfile, ga/19.0.0.3/kernel/Dockerfile.centos
Cleaning up the yum commands in our centos Dockerfiles as mentioned in https://github.com/docker-library/official-images/pull/5621
=> Clean up yum commands in centos Dockerfiles

test/verify.sh
Adding longer sleep times to avoid intermittent errors stopping containers (while the real problem is investigated).  Also adding better output for debugging test breaks.
=> Better debug and wait times in image tests

ga/19.0.0.3/kernel/Dockerfile
This PR is for issue #247 
Modified the `Dockerfile` to uninstalled `wget` and `unzip` packages after using them.
=> Uninstall packages that are no longer needed

ga/18.0.0.4/javaee7/Dockerfile.ubi-min, ga/18.0.0.4/javaee8/Dockerfile.ubi-min, ga/18.0.0.4/kernel/Dockerfile.ubi-min, ga/18.0.0.4/microProfile1/Dockerfile.ubi-min, ga/18.0.0.4/microProfile2/Dockerfile.ubi-min, ga/18.0.0.4/springBoot1/Dockerfile.ubi-min, ga/18.0.0.4/springBoot2/Dockerfile.ubi-min, ga/18.0.0.4/webProfile7/Dockerfile.ubi-min, ga/18.0.0.4/webProfile8/Dockerfile.ubi-min, ga/19.0.0.3/javaee7/Dockerfile.ubi-min, ga/19.0.0.3/javaee8/Dockerfile.ubi-min, ga/19.0.0.3/kernel/Dockerfile.ubi-min, ga/19.0.0.3/microProfile1/Dockerfile.ubi-min, ga/19.0.0.3/microProfile2/Dockerfile.ubi-min, ga/19.0.0.3/springBoot1/Dockerfile.ubi-min, ga/19.0.0.3/springBoot2/Dockerfile.ubi-min, ga/19.0.0.3/webProfile7/Dockerfile.ubi-min, ga/19.0.0.3/webProfile8/Dockerfile.ubi-min, ga/19.0.0.4/javaee7/Dockerfile.ubi-min, ga/19.0.0.4/javaee8/Dockerfile.ubi-min, ga/19.0.0.4/kernel/Dockerfile.ubi-min, ga/19.0.0.4/microProfile1/Dockerfile.ubi-min, ga/19.0.0.4/microProfile2/Dockerfile.ubi-min, ga/19.0.0.4/springBoot1/Dockerfile.ubi-min, ga/19.0.0.4/springBoot2/Dockerfile.ubi-min, ga/19.0.0.4/webProfile7/Dockerfile.ubi-min, ga/19.0.0.4/webProfile8/Dockerfile.ubi-min
Add files required to build the WebSphere Liberty ubi-min images.
=> Add files to build WL ubi-min images

README.md, ga/19.0.0.x/openshiftScan
* Updating docs to point to `.x` branch
* Making sure we keep the openshift scan script.
=> Docs update

test/verify.sh
Working to speed up the builds on Travis for this repository, because currently we are hitting a timeout after 2 hours.
=> Speed up ci.docker Travis builds

README.md, ga/latest/kernel/README.md
Made updates to the README file to improve clarity for the user.
https://github.ibm.com/WASCloudPrivate/roadmap-cloudpaks/issues/339
=> Update README for cloudpaks issue #339

ga/latest/kernel/helpers/build/configuration_snippets/ssl.xml
Deleted `ssl.xml` since it got replaced by `keystore.xml`
=> Deleted unnecessary file

beta/Dockerfile, ga/latest/kernel/Dockerfile, ga/latest/kernel/Dockerfile.centos, ga/latest/kernel/Dockerfile.java11, ga/latest/kernel/Dockerfile.ubi-min, ga/latest/kernel/licenses/en.html, ga/latest/kernel/licenses/non_ibm_license.html, ga/latest/kernel/licenses/notices.html
Update images for the 19.0.0.10 release
=> Updates for 19.0.0.10 release

ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/licenses/en.html, ga/latest/kernel/licenses/non_ibm_license.html, ga/latest/kernel/licenses/notices.html
Update dockerfiles and licenses for 19.0.0.11
=> Update to 19.0.0.11 release

ga/19.0.0.12/full/Dockerfile.ubi.adoptopenjdk11, ga/19.0.0.12/full/Dockerfile.ubi.adoptopenjdk8, ga/19.0.0.12/full/Dockerfile.ubi.ibmjava8, ga/19.0.0.12/full/Dockerfile.ubuntu.ibmjava8, ga/latest/full/Dockerfile.ubi.adoptopenjdk11, ga/latest/full/Dockerfile.ubi.adoptopenjdk8, ga/latest/full/Dockerfile.ubi.ibmjava8, ga/latest/full/Dockerfile.ubuntu.ibmjava8
=> Using baseBundle

beta/Dockerfile, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/licenses/en.html, ga/latest/kernel/licenses/non_ibm_license.html, ga/latest/kernel/licenses/notices.html
Update Dockerfiles and licenses for 20.0.0.1 release
=> Update for 20.0.0.1 release

beta/Dockerfile, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/licenses/en.html, ga/latest/kernel/licenses/non_ibm_license.html, ga/latest/kernel/licenses/notices.html
Dockerfile and license updates for 20.0.0.2 release
=> WIP: Updates for 20.0.0.2 release

beta/Dockerfile, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/licenses/en.html, ga/latest/kernel/licenses/non_ibm_license.html, ga/latest/kernel/licenses/notices.html
Dockerfile updates for the 20.0.0.4 release
=> Updates for 20.0.0.4 release

ga/latest/full/Dockerfile.ubi.adoptopenjdk11, ga/latest/full/Dockerfile.ubi.adoptopenjdk8, ga/latest/full/Dockerfile.ubi.ibmjava8, ga/latest/full/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk11, ga/latest/kernel/Dockerfile.ubi.adoptopenjdk8, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, test/build.sh, test/verify.sh
- Removes generated folder that shouldn't be there on startup
- See builds: https://travis-ci.org/github/WASdev/ci.docker/builds/674579110
=> Fix keystore issue in default image builds

README.md, ga/latest/kernel/helpers/build/populate_scc.sh
Port of https://github.com/OpenLiberty/ci.docker/pull/188 for WAS.
=> Fix potential max heap issues with OpenJ9 SCCs

README.md
- Added a new section for Known Issues
=> Added a new section for Known Issues

ga/20.0.0.3/kernel/helpers/build/configure.sh, ga/20.0.0.3/kernel/helpers/build/populate_scc.sh, ga/20.0.0.3/kernel/helpers/runtime/docker-server.sh, ga/20.0.0.6/kernel/helpers/build/configure.sh, ga/20.0.0.6/kernel/helpers/build/infinispan-client-setup.sh, ga/20.0.0.6/kernel/helpers/build/populate_scc.sh, ga/20.0.0.6/kernel/helpers/runtime/docker-server.sh, ga/20.0.0.8/kernel/helpers/build/configure.sh, ga/20.0.0.8/kernel/helpers/build/infinispan-client-setup.sh, ga/20.0.0.8/kernel/helpers/build/populate_scc.sh, ga/20.0.0.8/kernel/helpers/runtime/docker-server.sh, ga/latest/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/infinispan-client-setup.sh, ga/latest/kernel/helpers/build/populate_scc.sh, ga/latest/kernel/helpers/runtime/docker-server.sh, test/build.sh, test/buildAll.sh, test/verify.sh, tools/checkRepositorySync.sh, tools/syncRepository.sh, tools/updateBeta.sh
Please mind the two newlines my IDE appended.
I left it in because a unix file must always end with one.
=> Add license headers, fixes #355.

ga/20.0.0.11/images.txt
Add the 20.0.0.11 tags for the images.txt in that release.
=> Fix images.txt for 20.0.0.11

beta/README.md, ga/20.0.0.12/images.txt, ga/latest/images.txt
Signed-off-by: leochr <leojc@ca.ibm.com>
=> Add beta deprecation notice and update images.txt

ga/21.0.0.11/kernel/Dockerfile.ubi.openjdk11, ga/21.0.0.11/kernel/Dockerfile.ubi.openjdk8, ga/21.0.0.6/kernel/Dockerfile.ubi.openjdk11, ga/21.0.0.6/kernel/Dockerfile.ubi.openjdk8, ga/21.0.0.9/kernel/Dockerfile.ubi.openjdk11, ga/21.0.0.9/kernel/Dockerfile.ubi.openjdk8, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk8
Signed-off-by: leochr <leojc@ca.ibm.com>
=> Update the base tags of OpenJ9 Java images on UBI

ga/21.0.0.12/kernel/helpers/build/configure.sh, ga/22.0.0.3/kernel/helpers/build/configure.sh, ga/22.0.0.5/kernel/helpers/build/configure.sh, ga/latest/kernel/helpers/build/configure.sh
PR for https://github.com/WASdev/ci.docker/issues/449
=> Add ability to skip feature install step

docs/icr-images.md
List 22.0.0.9 images and remove 22.0.0.3 images
=> Update ICR images for 22.0.0.9

ga/23.0.0.3/kernel/Dockerfile.ubi.ibmjava8, ga/23.0.0.3/kernel/Dockerfile.ubi.openjdk11, ga/23.0.0.3/kernel/Dockerfile.ubi.openjdk17, ga/23.0.0.3/kernel/Dockerfile.ubi.openjdk8, ga/23.0.0.3/kernel/Dockerfile.ubuntu.ibmjava8, ga/23.0.0.3/kernel/Dockerfile.ubuntu.openjdk11, ga/23.0.0.3/kernel/Dockerfile.ubuntu.openjdk17, ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk17, ga/latest/kernel/Dockerfile.ubi.openjdk8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.openjdk11, ga/latest/kernel/Dockerfile.ubuntu.openjdk17
Update the version to the correct format:
ENV LIBERTY_VERSION 23.0.0.3 --> ENV LIBERTY_VERSION 23.0.0_3
=> Update Liberty version env to 23.0.0.3

docs/icr-images.md
**Merge this ONLY after 23.0.0.12 images are published to icr.io**
- List the images for 23.0.0.12
=> List the images for 23.0.0.12

ga/latest/kernel/Dockerfile.ubi.ibmjava8, ga/latest/kernel/Dockerfile.ubi.openjdk11, ga/latest/kernel/Dockerfile.ubi.openjdk17, ga/latest/kernel/Dockerfile.ubi.openjdk21, ga/latest/kernel/Dockerfile.ubi.openjdk8, ga/latest/kernel/Dockerfile.ubuntu.ibmjava8, ga/latest/kernel/Dockerfile.ubuntu.openjdk11, ga/latest/kernel/Dockerfile.ubuntu.openjdk17
Deals with OpenLiberty/ci.docker#594
=> Ensure all helper scripts have execute permission

ga/25.0.0.10/kernel/Dockerfile.ubi9-minimal.openjdk25, ga/latest/kernel/Dockerfile.ubi9-minimal.openjdk25
Update Semeru 25 JRE to GA/production image
=> Update Semeru 25 JRE base image
